### ISSUE TITLE
font color & size

### ISSUE THREAD

**Issue by greedyvegan** [ngnijland/MMM-text-clock#36]
two things:

- I'd like to make the font that's the current time another color and the inactive letters darker/dimmer.
- I'd like a size in the middle of xsmall-small or small-medium, is there a way to modify the height/width? 
 
(custom.css is doing absolutely nothing for me)

**Comment by ngnijland** [comment]
Hi @greedyvegan!

These are two very specific request that might not resonate with other users. Therefore, I suggest using custom CSS. I just tried to use custom css to overwrite styles of the clock, but I see that you mentioned that it doesn't work for you. Let's try to debug that.

These are the steps I took to use custom CSS to overwrite clock styles:
1. Create a file called `custom.css` in the CSS folder of MagicMirror: `MagicMirror/css/custom.css`
2. I use MagicMirror's default styling classes, so you should overwrite those.

**To overwrite the color the letters showing the current time:**
```css
// To overwrite all elements styled with the `bright` class in all modules:
.bright {
  color: yellow;
}

// To only overwrite the elements styled with the `bright` class in the `MMM-text-clock` module:
.MMM-text-clock .bright {
  color: yellow;
}
```

**To overwrite the color the letters that are inactive:**
```css
// To overwrite all elements styled with the `dimmed` class in all modules:
.dimmed {
  color: purple;
}

// To only overwrite the elements styled with the `dimmed` class in the `MMM-text-clock` module:
.MMM-text-clock .dimmed {
  color: purple;
}
```

**To modify the width/height:**
There is no way to directly modify the width and the height of the clock. The width and the height are determined by the font-size and the spacing between the letters. You could overwrite the style of those two individually to achieve the exact style you want.

To overwrite the font-size:
```css
.MMM-text-clock .letters {
  font-size: 30px;
}
```

To overwrite the spacing between the letters:
```css
.MMM-text-clock .grid {
  grid-gap: 30px;
}
```

I hope this helps!
